DATASET_NAME: 'ONERA.ROOM'
OWNER: 'Joris GUERRY & Bertrand LE SAUX (ONERA)'
VOC_DIR: 'bb/voc/'
XML_PREFIX: 'bb/bb.xml'
RGB_PREFIX: 'image/0'
D_PREFIX: 'depth_8bits/0'
CLASSES: ["null", "bag", "bike", "box", "cabinet", "car", "ceiling", "chair", "computer", "door", "emergency sign", "extinguisher", "floor", "lamp", "paper", "person", "phone", "poster", "screen", "shelf", "table", "wall", "whiteboard", "window"]
